[package]
name = "flashpdf-core"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
itoa = "=1.0.18"
miniz_oxide = { version = "=0.9.1", default-features = false, features = ["with-alloc"] }
pdf-writer = "=0.15.0"

[dev-dependencies]
lopdf = { version = "0.45", default-features = false }
